name: spectral
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - imagecodecs[all]
    - --editable .
  - numcodecs
  - tifffile
  - ipykernel
  - pandas
  - openpyxl
  - matplotlib
  - xarray
  - statsmodels
